/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as components from "../components/index.js";
import { LivepeerError } from "./livepeererror.js";

/**
 * HTTP error response model.
 */
export type HTTPErrorData = {
  /**
   * Detailed error information.
   */
  detail: components.APIError;
};

/**
 * HTTP error response model.
 */
export class HTTPError extends LivepeerError {
  /**
   * Detailed error information.
   */
  detail: components.APIError;

  /** The original data that was passed to this error instance. */
  data$: HTTPErrorData;

  constructor(
    err: HTTPErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.detail = err.detail;

    this.name = "HTTPError";
  }
}

/** @internal */
export const HTTPError$inboundSchema: z.ZodType<
  HTTPError,
  z.ZodTypeDef,
  unknown
> = z.object({
  detail: components.APIError$inboundSchema,
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new HTTPError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
