/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @livepeer/ai SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx generateTextToImage.example.ts
 */

import { Livepeer } from "@livepeer/ai";

const livepeer = new Livepeer({
  httpBearer: "<YOUR_BEARER_TOKEN_HERE>",
});

async function main() {
  const result = await livepeer.generate.textToImage({
    prompt: "<value>",
  });

  console.log(result);
}

main().catch(console.error);
