workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    livepeer-ai-OAS:
        inputs:
            - location: https://raw.githubusercontent.com/livepeer/ai-worker/main/runner/gateway.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/livepeer-ai/livepeer-ai/livepeer-ai-oas
targets:
    livepeer-ai-ts:
        target: typescript
        source: livepeer-ai-OAS
        publish:
            npm:
                token: $npm_token
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/livepeer-ai/livepeer-ai/code-samples-typescript-livepeer-ts
