/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type AudioToTextResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Successful Response
   */
  textResponse?: components.TextResponse | undefined;
};

/** @internal */
export const AudioToTextResponse$inboundSchema: z.ZodType<
  AudioToTextResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  TextResponse: components.TextResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
    "TextResponse": "textResponse",
  });
});

/** @internal */
export type AudioToTextResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  TextResponse?: components.TextResponse$Outbound | undefined;
};

/** @internal */
export const AudioToTextResponse$outboundSchema: z.ZodType<
  AudioToTextResponse$Outbound,
  z.ZodTypeDef,
  AudioToTextResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
  textResponse: components.TextResponse$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
    textResponse: "TextResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AudioToTextResponse$ {
  /** @deprecated use `AudioToTextResponse$inboundSchema` instead. */
  export const inboundSchema = AudioToTextResponse$inboundSchema;
  /** @deprecated use `AudioToTextResponse$outboundSchema` instead. */
  export const outboundSchema = AudioToTextResponse$outboundSchema;
  /** @deprecated use `AudioToTextResponse$Outbound` instead. */
  export type Outbound = AudioToTextResponse$Outbound;
}
