/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GenImageToTextResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Successful Response
   */
  imageToTextResponse?: components.ImageToTextResponse | undefined;
};

/** @internal */
export const GenImageToTextResponse$inboundSchema: z.ZodType<
  GenImageToTextResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  ImageToTextResponse: components.ImageToTextResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
    "ImageToTextResponse": "imageToTextResponse",
  });
});

export function genImageToTextResponseFromJSON(
  jsonString: string,
): SafeParseResult<GenImageToTextResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GenImageToTextResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenImageToTextResponse' from JSON`,
  );
}
