/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type GenLiveVideoToVideoResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Successful Response
   */
  liveVideoToVideoResponse?: components.LiveVideoToVideoResponse | undefined;
};

/** @internal */
export const GenLiveVideoToVideoResponse$inboundSchema: z.ZodType<
  GenLiveVideoToVideoResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  LiveVideoToVideoResponse: components.LiveVideoToVideoResponse$inboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
    "LiveVideoToVideoResponse": "liveVideoToVideoResponse",
  });
});

/** @internal */
export type GenLiveVideoToVideoResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  LiveVideoToVideoResponse?:
    | components.LiveVideoToVideoResponse$Outbound
    | undefined;
};

/** @internal */
export const GenLiveVideoToVideoResponse$outboundSchema: z.ZodType<
  GenLiveVideoToVideoResponse$Outbound,
  z.ZodTypeDef,
  GenLiveVideoToVideoResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
  liveVideoToVideoResponse: components.LiveVideoToVideoResponse$outboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
    liveVideoToVideoResponse: "LiveVideoToVideoResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GenLiveVideoToVideoResponse$ {
  /** @deprecated use `GenLiveVideoToVideoResponse$inboundSchema` instead. */
  export const inboundSchema = GenLiveVideoToVideoResponse$inboundSchema;
  /** @deprecated use `GenLiveVideoToVideoResponse$outboundSchema` instead. */
  export const outboundSchema = GenLiveVideoToVideoResponse$outboundSchema;
  /** @deprecated use `GenLiveVideoToVideoResponse$Outbound` instead. */
  export type Outbound = GenLiveVideoToVideoResponse$Outbound;
}
