/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GenLiveVideoToVideoRequest = {
  requestID?: string | undefined;
  streamID?: string | undefined;
  liveVideoToVideoParams: components.LiveVideoToVideoParams;
};

export type GenLiveVideoToVideoResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Successful Response
   */
  liveVideoToVideoResponse?: components.LiveVideoToVideoResponse | undefined;
};

/** @internal */
export const GenLiveVideoToVideoRequest$inboundSchema: z.ZodType<
  GenLiveVideoToVideoRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  requestID: z.string().optional(),
  streamID: z.string().optional(),
  LiveVideoToVideoParams: components.LiveVideoToVideoParams$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "LiveVideoToVideoParams": "liveVideoToVideoParams",
  });
});

/** @internal */
export type GenLiveVideoToVideoRequest$Outbound = {
  requestID?: string | undefined;
  streamID?: string | undefined;
  LiveVideoToVideoParams: components.LiveVideoToVideoParams$Outbound;
};

/** @internal */
export const GenLiveVideoToVideoRequest$outboundSchema: z.ZodType<
  GenLiveVideoToVideoRequest$Outbound,
  z.ZodTypeDef,
  GenLiveVideoToVideoRequest
> = z.object({
  requestID: z.string().optional(),
  streamID: z.string().optional(),
  liveVideoToVideoParams: components.LiveVideoToVideoParams$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    liveVideoToVideoParams: "LiveVideoToVideoParams",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GenLiveVideoToVideoRequest$ {
  /** @deprecated use `GenLiveVideoToVideoRequest$inboundSchema` instead. */
  export const inboundSchema = GenLiveVideoToVideoRequest$inboundSchema;
  /** @deprecated use `GenLiveVideoToVideoRequest$outboundSchema` instead. */
  export const outboundSchema = GenLiveVideoToVideoRequest$outboundSchema;
  /** @deprecated use `GenLiveVideoToVideoRequest$Outbound` instead. */
  export type Outbound = GenLiveVideoToVideoRequest$Outbound;
}

export function genLiveVideoToVideoRequestToJSON(
  genLiveVideoToVideoRequest: GenLiveVideoToVideoRequest,
): string {
  return JSON.stringify(
    GenLiveVideoToVideoRequest$outboundSchema.parse(genLiveVideoToVideoRequest),
  );
}

export function genLiveVideoToVideoRequestFromJSON(
  jsonString: string,
): SafeParseResult<GenLiveVideoToVideoRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GenLiveVideoToVideoRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenLiveVideoToVideoRequest' from JSON`,
  );
}

/** @internal */
export const GenLiveVideoToVideoResponse$inboundSchema: z.ZodType<
  GenLiveVideoToVideoResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  LiveVideoToVideoResponse: components.LiveVideoToVideoResponse$inboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
    "LiveVideoToVideoResponse": "liveVideoToVideoResponse",
  });
});

/** @internal */
export type GenLiveVideoToVideoResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  LiveVideoToVideoResponse?:
    | components.LiveVideoToVideoResponse$Outbound
    | undefined;
};

/** @internal */
export const GenLiveVideoToVideoResponse$outboundSchema: z.ZodType<
  GenLiveVideoToVideoResponse$Outbound,
  z.ZodTypeDef,
  GenLiveVideoToVideoResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
  liveVideoToVideoResponse: components.LiveVideoToVideoResponse$outboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
    liveVideoToVideoResponse: "LiveVideoToVideoResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GenLiveVideoToVideoResponse$ {
  /** @deprecated use `GenLiveVideoToVideoResponse$inboundSchema` instead. */
  export const inboundSchema = GenLiveVideoToVideoResponse$inboundSchema;
  /** @deprecated use `GenLiveVideoToVideoResponse$outboundSchema` instead. */
  export const outboundSchema = GenLiveVideoToVideoResponse$outboundSchema;
  /** @deprecated use `GenLiveVideoToVideoResponse$Outbound` instead. */
  export type Outbound = GenLiveVideoToVideoResponse$Outbound;
}

export function genLiveVideoToVideoResponseToJSON(
  genLiveVideoToVideoResponse: GenLiveVideoToVideoResponse,
): string {
  return JSON.stringify(
    GenLiveVideoToVideoResponse$outboundSchema.parse(
      genLiveVideoToVideoResponse,
    ),
  );
}

export function genLiveVideoToVideoResponseFromJSON(
  jsonString: string,
): SafeParseResult<GenLiveVideoToVideoResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GenLiveVideoToVideoResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenLiveVideoToVideoResponse' from JSON`,
  );
}
