/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GenLLMResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Successful Response
   */
  llmResponse?: components.LLMResponse | undefined;
};

/** @internal */
export const GenLLMResponse$inboundSchema: z.ZodType<
  GenLLMResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  LLMResponse: components.LLMResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
    "LLMResponse": "llmResponse",
  });
});

export function genLLMResponseFromJSON(
  jsonString: string,
): SafeParseResult<GenLLMResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GenLLMResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenLLMResponse' from JSON`,
  );
}
