/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GenSegmentAnything2Response = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Successful Response
   */
  masksResponse?: components.MasksResponse | undefined;
};

/** @internal */
export const GenSegmentAnything2Response$inboundSchema: z.ZodType<
  GenSegmentAnything2Response,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  MasksResponse: components.MasksResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
    "MasksResponse": "masksResponse",
  });
});

export function genSegmentAnything2ResponseFromJSON(
  jsonString: string,
): SafeParseResult<GenSegmentAnything2Response, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GenSegmentAnything2Response$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenSegmentAnything2Response' from JSON`,
  );
}
