/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type ImageToVideoResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Successful Response
   */
  videoResponse?: components.VideoResponse | undefined;
};

/** @internal */
export const ImageToVideoResponse$inboundSchema: z.ZodType<
  ImageToVideoResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  VideoResponse: components.VideoResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
    "VideoResponse": "videoResponse",
  });
});

/** @internal */
export type ImageToVideoResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  VideoResponse?: components.VideoResponse$Outbound | undefined;
};

/** @internal */
export const ImageToVideoResponse$outboundSchema: z.ZodType<
  ImageToVideoResponse$Outbound,
  z.ZodTypeDef,
  ImageToVideoResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
  videoResponse: components.VideoResponse$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
    videoResponse: "VideoResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ImageToVideoResponse$ {
  /** @deprecated use `ImageToVideoResponse$inboundSchema` instead. */
  export const inboundSchema = ImageToVideoResponse$inboundSchema;
  /** @deprecated use `ImageToVideoResponse$outboundSchema` instead. */
  export const outboundSchema = ImageToVideoResponse$outboundSchema;
  /** @deprecated use `ImageToVideoResponse$Outbound` instead. */
  export type Outbound = ImageToVideoResponse$Outbound;
}
