/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * API error response model.
 */
export type APIError = {
  /**
   * The error message.
   */
  msg: string;
};

/** @internal */
export const APIError$inboundSchema: z.ZodType<
  APIError,
  z.ZodTypeDef,
  unknown
> = z.object({
  msg: z.string(),
});

export function apiErrorFromJSON(
  jsonString: string,
): SafeParseResult<APIError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => APIError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'APIError' from JSON`,
  );
}
