/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { MediaURL, MediaURL$inboundSchema } from "./mediaurl.js";

/**
 * Response model for audio generation.
 */
export type AudioResponse = {
  /**
   * A URL from which media can be accessed.
   */
  audio: MediaURL;
};

/** @internal */
export const AudioResponse$inboundSchema: z.ZodType<
  AudioResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  audio: MediaURL$inboundSchema,
});

export function audioResponseFromJSON(
  jsonString: string,
): SafeParseResult<AudioResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AudioResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AudioResponse' from JSON`,
  );
}
