/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { blobLikeSchema } from "../../types/blobs.js";

export type Image = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type BodyGenImageToImage = {
  /**
   * Text prompt(s) to guide image generation.
   */
  prompt: string;
  /**
   * Uploaded image to modify with the pipeline.
   */
  image: Image | Blob;
  /**
   * Hugging Face model ID used for image generation.
   */
  modelId?: string | undefined;
  /**
   * A LoRA (Low-Rank Adaptation) model and its corresponding weight for image generation. Example: { "latent-consistency/lcm-lora-sdxl": 1.0, "nerijs/pixel-art-xl": 1.2}.
   */
  loras?: string | undefined;
  /**
   * Degree of transformation applied to the reference image (0 to 1).
   */
  strength?: number | undefined;
  /**
   * Encourages model to generate images closely linked to the text prompt (higher values may reduce image quality).
   */
  guidanceScale?: number | undefined;
  /**
   * Degree to which the generated image is pushed towards the initial image.
   */
  imageGuidanceScale?: number | undefined;
  /**
   * Text prompt(s) to guide what to exclude from image generation. Ignored if guidance_scale < 1.
   */
  negativePrompt?: string | undefined;
  /**
   * Perform a safety check to estimate if generated images could be offensive or harmful.
   */
  safetyCheck?: boolean | undefined;
  /**
   * Seed for random number generation.
   */
  seed?: number | undefined;
  /**
   * Number of denoising steps. More steps usually lead to higher quality images but slower inference. Modulated by strength.
   */
  numInferenceSteps?: number | undefined;
  /**
   * Number of images to generate per prompt.
   */
  numImagesPerPrompt?: number | undefined;
};

/** @internal */
export type Image$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const Image$outboundSchema: z.ZodType<
  Image$Outbound,
  z.ZodTypeDef,
  Image
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
});

export function imageToJSON(image: Image): string {
  return JSON.stringify(Image$outboundSchema.parse(image));
}

/** @internal */
export type BodyGenImageToImage$Outbound = {
  prompt: string;
  image: Image$Outbound | Blob;
  model_id: string;
  loras: string;
  strength: number;
  guidance_scale: number;
  image_guidance_scale: number;
  negative_prompt: string;
  safety_check: boolean;
  seed?: number | undefined;
  num_inference_steps: number;
  num_images_per_prompt: number;
};

/** @internal */
export const BodyGenImageToImage$outboundSchema: z.ZodType<
  BodyGenImageToImage$Outbound,
  z.ZodTypeDef,
  BodyGenImageToImage
> = z.object({
  prompt: z.string(),
  image: z.lazy(() => Image$outboundSchema).or(blobLikeSchema),
  modelId: z.string().default(""),
  loras: z.string().default(""),
  strength: z.number().default(0.8),
  guidanceScale: z.number().default(7.5),
  imageGuidanceScale: z.number().default(1.5),
  negativePrompt: z.string().default(""),
  safetyCheck: z.boolean().default(true),
  seed: z.number().int().optional(),
  numInferenceSteps: z.number().int().default(100),
  numImagesPerPrompt: z.number().int().default(1),
}).transform((v) => {
  return remap$(v, {
    modelId: "model_id",
    guidanceScale: "guidance_scale",
    imageGuidanceScale: "image_guidance_scale",
    negativePrompt: "negative_prompt",
    safetyCheck: "safety_check",
    numInferenceSteps: "num_inference_steps",
    numImagesPerPrompt: "num_images_per_prompt",
  });
});

export function bodyGenImageToImageToJSON(
  bodyGenImageToImage: BodyGenImageToImage,
): string {
  return JSON.stringify(
    BodyGenImageToImage$outboundSchema.parse(bodyGenImageToImage),
  );
}
