/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { blobLikeSchema } from "../../types/blobs.js";

export type BodyGenImageToTextImage = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type BodyGenImageToText = {
  /**
   * Uploaded image to transform with the pipeline.
   */
  image: BodyGenImageToTextImage | Blob;
  /**
   * Text prompt(s) to guide transformation.
   */
  prompt?: string | undefined;
  /**
   * Hugging Face model ID used for transformation.
   */
  modelId?: string | undefined;
};

/** @internal */
export type BodyGenImageToTextImage$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const BodyGenImageToTextImage$outboundSchema: z.ZodType<
  BodyGenImageToTextImage$Outbound,
  z.ZodTypeDef,
  BodyGenImageToTextImage
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
});

export function bodyGenImageToTextImageToJSON(
  bodyGenImageToTextImage: BodyGenImageToTextImage,
): string {
  return JSON.stringify(
    BodyGenImageToTextImage$outboundSchema.parse(bodyGenImageToTextImage),
  );
}

/** @internal */
export type BodyGenImageToText$Outbound = {
  image: BodyGenImageToTextImage$Outbound | Blob;
  prompt: string;
  model_id: string;
};

/** @internal */
export const BodyGenImageToText$outboundSchema: z.ZodType<
  BodyGenImageToText$Outbound,
  z.ZodTypeDef,
  BodyGenImageToText
> = z.object({
  image: z.lazy(() => BodyGenImageToTextImage$outboundSchema).or(
    blobLikeSchema,
  ),
  prompt: z.string().default(""),
  modelId: z.string().default(""),
}).transform((v) => {
  return remap$(v, {
    modelId: "model_id",
  });
});

export function bodyGenImageToTextToJSON(
  bodyGenImageToText: BodyGenImageToText,
): string {
  return JSON.stringify(
    BodyGenImageToText$outboundSchema.parse(bodyGenImageToText),
  );
}
