/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { blobLikeSchema } from "../../types/blobs.js";

export type BodyGenUpscaleImage = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type BodyGenUpscale = {
  /**
   * Text prompt(s) to guide upscaled image generation.
   */
  prompt: string;
  /**
   * Uploaded image to modify with the pipeline.
   */
  image: BodyGenUpscaleImage | Blob;
  /**
   * Hugging Face model ID used for upscaled image generation.
   */
  modelId?: string | undefined;
  /**
   * Perform a safety check to estimate if generated images could be offensive or harmful.
   */
  safetyCheck?: boolean | undefined;
  /**
   * Seed for random number generation.
   */
  seed?: number | undefined;
  /**
   * Number of denoising steps. More steps usually lead to higher quality images but slower inference. Modulated by strength.
   */
  numInferenceSteps?: number | undefined;
};

/** @internal */
export type BodyGenUpscaleImage$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const BodyGenUpscaleImage$outboundSchema: z.ZodType<
  BodyGenUpscaleImage$Outbound,
  z.ZodTypeDef,
  BodyGenUpscaleImage
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
});

export function bodyGenUpscaleImageToJSON(
  bodyGenUpscaleImage: BodyGenUpscaleImage,
): string {
  return JSON.stringify(
    BodyGenUpscaleImage$outboundSchema.parse(bodyGenUpscaleImage),
  );
}

/** @internal */
export type BodyGenUpscale$Outbound = {
  prompt: string;
  image: BodyGenUpscaleImage$Outbound | Blob;
  model_id: string;
  safety_check: boolean;
  seed?: number | undefined;
  num_inference_steps: number;
};

/** @internal */
export const BodyGenUpscale$outboundSchema: z.ZodType<
  BodyGenUpscale$Outbound,
  z.ZodTypeDef,
  BodyGenUpscale
> = z.object({
  prompt: z.string(),
  image: z.lazy(() => BodyGenUpscaleImage$outboundSchema).or(blobLikeSchema),
  modelId: z.string().default(""),
  safetyCheck: z.boolean().default(true),
  seed: z.number().int().optional(),
  numInferenceSteps: z.number().int().default(75),
}).transform((v) => {
  return remap$(v, {
    modelId: "model_id",
    safetyCheck: "safety_check",
    numInferenceSteps: "num_inference_steps",
  });
});

export function bodyGenUpscaleToJSON(bodyGenUpscale: BodyGenUpscale): string {
  return JSON.stringify(BodyGenUpscale$outboundSchema.parse(bodyGenUpscale));
}
