/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { blobLikeSchema } from "../../types/blobs.js";

export type Audio = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type BodyGenAudioToText = {
  /**
   * Uploaded audio file to be transcribed.
   */
  audio: Audio | Blob;
  /**
   * Hugging Face model ID used for transcription.
   */
  modelId?: string | undefined;
  /**
   * Return timestamps for the transcribed text. Supported values: 'sentence', 'word', or a string boolean ('true' or 'false'). Default is 'true' ('sentence'). 'false' means no timestamps. 'word' means word-based timestamps.
   */
  returnTimestamps?: string | undefined;
};

/** @internal */
export type Audio$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const Audio$outboundSchema: z.ZodType<
  Audio$Outbound,
  z.ZodTypeDef,
  Audio
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
});

export function audioToJSON(audio: Audio): string {
  return JSON.stringify(Audio$outboundSchema.parse(audio));
}

/** @internal */
export type BodyGenAudioToText$Outbound = {
  audio: Audio$Outbound | Blob;
  model_id: string;
  return_timestamps: string;
};

/** @internal */
export const BodyGenAudioToText$outboundSchema: z.ZodType<
  BodyGenAudioToText$Outbound,
  z.ZodTypeDef,
  BodyGenAudioToText
> = z.object({
  audio: z.lazy(() => Audio$outboundSchema).or(blobLikeSchema),
  modelId: z.string().default(""),
  returnTimestamps: z.string().default("true"),
}).transform((v) => {
  return remap$(v, {
    modelId: "model_id",
    returnTimestamps: "return_timestamps",
  });
});

export function bodyGenAudioToTextToJSON(
  bodyGenAudioToText: BodyGenAudioToText,
): string {
  return JSON.stringify(
    BodyGenAudioToText$outboundSchema.parse(bodyGenAudioToText),
  );
}
