/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { blobLikeSchema } from "../../types/blobs.js";

export type BodyGenImageToVideoImage = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type BodyGenImageToVideo = {
  /**
   * Uploaded image to generate a video from.
   */
  image: BodyGenImageToVideoImage | Blob;
  /**
   * Hugging Face model ID used for video generation.
   */
  modelId?: string | undefined;
  /**
   * The height in pixels of the generated video.
   */
  height?: number | undefined;
  /**
   * The width in pixels of the generated video.
   */
  width?: number | undefined;
  /**
   * The frames per second of the generated video.
   */
  fps?: number | undefined;
  /**
   * Used for conditioning the amount of motion for the generation. The higher the number the more motion will be in the video.
   */
  motionBucketId?: number | undefined;
  /**
   * Amount of noise added to the conditioning image. Higher values reduce resemblance to the conditioning image and increase motion.
   */
  noiseAugStrength?: number | undefined;
  /**
   * Perform a safety check to estimate if generated images could be offensive or harmful.
   */
  safetyCheck?: boolean | undefined;
  /**
   * Seed for random number generation.
   */
  seed?: number | undefined;
  /**
   * Number of denoising steps. More steps usually lead to higher quality images but slower inference. Modulated by strength.
   */
  numInferenceSteps?: number | undefined;
};

/** @internal */
export type BodyGenImageToVideoImage$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const BodyGenImageToVideoImage$outboundSchema: z.ZodType<
  BodyGenImageToVideoImage$Outbound,
  z.ZodTypeDef,
  BodyGenImageToVideoImage
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
});

export function bodyGenImageToVideoImageToJSON(
  bodyGenImageToVideoImage: BodyGenImageToVideoImage,
): string {
  return JSON.stringify(
    BodyGenImageToVideoImage$outboundSchema.parse(bodyGenImageToVideoImage),
  );
}

/** @internal */
export type BodyGenImageToVideo$Outbound = {
  image: BodyGenImageToVideoImage$Outbound | Blob;
  model_id: string;
  height: number;
  width: number;
  fps: number;
  motion_bucket_id: number;
  noise_aug_strength: number;
  safety_check: boolean;
  seed?: number | undefined;
  num_inference_steps: number;
};

/** @internal */
export const BodyGenImageToVideo$outboundSchema: z.ZodType<
  BodyGenImageToVideo$Outbound,
  z.ZodTypeDef,
  BodyGenImageToVideo
> = z.object({
  image: z.lazy(() => BodyGenImageToVideoImage$outboundSchema).or(
    blobLikeSchema,
  ),
  modelId: z.string().default(""),
  height: z.number().int().default(576),
  width: z.number().int().default(1024),
  fps: z.number().int().default(6),
  motionBucketId: z.number().int().default(127),
  noiseAugStrength: z.number().default(0.02),
  safetyCheck: z.boolean().default(true),
  seed: z.number().int().optional(),
  numInferenceSteps: z.number().int().default(25),
}).transform((v) => {
  return remap$(v, {
    modelId: "model_id",
    motionBucketId: "motion_bucket_id",
    noiseAugStrength: "noise_aug_strength",
    safetyCheck: "safety_check",
    numInferenceSteps: "num_inference_steps",
  });
});

export function bodyGenImageToVideoToJSON(
  bodyGenImageToVideo: BodyGenImageToVideo,
): string {
  return JSON.stringify(
    BodyGenImageToVideo$outboundSchema.parse(bodyGenImageToVideo),
  );
}
