/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { blobLikeSchema } from "../../types/blobs.js";

export type BodyGenSegmentAnything2Image = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type BodyGenSegmentAnything2 = {
  /**
   * Image to segment.
   */
  image: BodyGenSegmentAnything2Image | Blob;
  /**
   * Hugging Face model ID used for image generation.
   */
  modelId?: string | undefined;
  /**
   * Nx2 array of point prompts to the model, where each point is in (X,Y) in pixels.
   */
  pointCoords?: string | undefined;
  /**
   * Labels for the point prompts, where 1 indicates a foreground point and 0 indicates a background point.
   */
  pointLabels?: string | undefined;
  /**
   * A length 4 array given as a box prompt to the model, in XYXY format.
   */
  box?: string | undefined;
  /**
   * A low-resolution mask input to the model, typically from a previous prediction iteration, with the form 1xHxW (H=W=256 for SAM).
   */
  maskInput?: string | undefined;
  /**
   * If true, the model will return three masks for ambiguous input prompts, often producing better masks than a single prediction.
   */
  multimaskOutput?: boolean | undefined;
  /**
   * If true, returns un-thresholded mask logits instead of a binary mask.
   */
  returnLogits?: boolean | undefined;
  /**
   * If true, the point coordinates will be normalized to the range [0,1], with point_coords expected to be with respect to image dimensions.
   */
  normalizeCoords?: boolean | undefined;
};

/** @internal */
export type BodyGenSegmentAnything2Image$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const BodyGenSegmentAnything2Image$outboundSchema: z.ZodType<
  BodyGenSegmentAnything2Image$Outbound,
  z.ZodTypeDef,
  BodyGenSegmentAnything2Image
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
});

export function bodyGenSegmentAnything2ImageToJSON(
  bodyGenSegmentAnything2Image: BodyGenSegmentAnything2Image,
): string {
  return JSON.stringify(
    BodyGenSegmentAnything2Image$outboundSchema.parse(
      bodyGenSegmentAnything2Image,
    ),
  );
}

/** @internal */
export type BodyGenSegmentAnything2$Outbound = {
  image: BodyGenSegmentAnything2Image$Outbound | Blob;
  model_id: string;
  point_coords?: string | undefined;
  point_labels?: string | undefined;
  box?: string | undefined;
  mask_input?: string | undefined;
  multimask_output: boolean;
  return_logits: boolean;
  normalize_coords: boolean;
};

/** @internal */
export const BodyGenSegmentAnything2$outboundSchema: z.ZodType<
  BodyGenSegmentAnything2$Outbound,
  z.ZodTypeDef,
  BodyGenSegmentAnything2
> = z.object({
  image: z.lazy(() => BodyGenSegmentAnything2Image$outboundSchema).or(
    blobLikeSchema,
  ),
  modelId: z.string().default(""),
  pointCoords: z.string().optional(),
  pointLabels: z.string().optional(),
  box: z.string().optional(),
  maskInput: z.string().optional(),
  multimaskOutput: z.boolean().default(true),
  returnLogits: z.boolean().default(true),
  normalizeCoords: z.boolean().default(true),
}).transform((v) => {
  return remap$(v, {
    modelId: "model_id",
    pointCoords: "point_coords",
    pointLabels: "point_labels",
    maskInput: "mask_input",
    multimaskOutput: "multimask_output",
    returnLogits: "return_logits",
    normalizeCoords: "normalize_coords",
  });
});

export function bodyGenSegmentAnything2ToJSON(
  bodyGenSegmentAnything2: BodyGenSegmentAnything2,
): string {
  return JSON.stringify(
    BodyGenSegmentAnything2$outboundSchema.parse(bodyGenSegmentAnything2),
  );
}
