/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A chunk of text with a timestamp.
 */
export type Chunk = {
  /**
   * The timestamp of the chunk.
   */
  timestamp: Array<any>;
  /**
   * The text of the chunk.
   */
  text: string;
};

/** @internal */
export const Chunk$inboundSchema: z.ZodType<Chunk, z.ZodTypeDef, unknown> = z
  .object({
    timestamp: z.array(z.any()),
    text: z.string(),
  });

export function chunkFromJSON(
  jsonString: string,
): SafeParseResult<Chunk, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Chunk$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Chunk' from JSON`,
  );
}
