/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Response model for text generation.
 */
export type ImageToTextResponse = {
  /**
   * The generated text.
   */
  text: string;
};

/** @internal */
export const ImageToTextResponse$inboundSchema: z.ZodType<
  ImageToTextResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  text: z.string(),
});

export function imageToTextResponseFromJSON(
  jsonString: string,
): SafeParseResult<ImageToTextResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageToTextResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageToTextResponse' from JSON`,
  );
}
