/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Media, Media$inboundSchema } from "./media.js";

/**
 * Response model for image generation.
 */
export type ImageResponse = {
  /**
   * The generated images.
   */
  images: Array<Media>;
};

/** @internal */
export const ImageResponse$inboundSchema: z.ZodType<
  ImageResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  images: z.array(Media$inboundSchema),
});

export function imageResponseFromJSON(
  jsonString: string,
): SafeParseResult<ImageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageResponse' from JSON`,
  );
}
