/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type LiveVideoToVideoParams = {
  /**
   * Source URL of the incoming stream to subscribe to.
   */
  subscribeUrl: string;
  /**
   * Destination URL of the outgoing stream to publish.
   */
  publishUrl: string;
  /**
   * URL for subscribing via Trickle protocol for updates in the live video-to-video generation params.
   */
  controlUrl?: string | undefined;
  /**
   * URL for publishing events via Trickle protocol for pipeline status and logs.
   */
  eventsUrl?: string | undefined;
  /**
   * Name of the pipeline to run in the live video to video job. Notice that this is named model_id for consistency with other routes, but it does not refer to a Hugging Face model ID. The exact model(s) depends on the pipeline implementation and might be configurable via the `params` argument.
   */
  modelId?: string | undefined;
  /**
   * Initial parameters for the pipeline.
   */
  params?: { [k: string]: any } | undefined;
  /**
   * The ID of the Gateway request (for logging purposes).
   */
  gatewayRequestId?: string | undefined;
  /**
   * The manifest ID from the orchestrator (for logging purposes).
   */
  manifestId?: string | undefined;
  /**
   * The Stream ID (for logging purposes).
   */
  streamId?: string | undefined;
};

/** @internal */
export type LiveVideoToVideoParams$Outbound = {
  subscribe_url: string;
  publish_url: string;
  control_url: string;
  events_url: string;
  model_id: string;
  params?: { [k: string]: any } | undefined;
  gateway_request_id: string;
  manifest_id: string;
  stream_id: string;
};

/** @internal */
export const LiveVideoToVideoParams$outboundSchema: z.ZodType<
  LiveVideoToVideoParams$Outbound,
  z.ZodTypeDef,
  LiveVideoToVideoParams
> = z.object({
  subscribeUrl: z.string(),
  publishUrl: z.string(),
  controlUrl: z.string().default(""),
  eventsUrl: z.string().default(""),
  modelId: z.string().default(""),
  params: z.record(z.any()).optional(),
  gatewayRequestId: z.string().default(""),
  manifestId: z.string().default(""),
  streamId: z.string().default(""),
}).transform((v) => {
  return remap$(v, {
    subscribeUrl: "subscribe_url",
    publishUrl: "publish_url",
    controlUrl: "control_url",
    eventsUrl: "events_url",
    modelId: "model_id",
    gatewayRequestId: "gateway_request_id",
    manifestId: "manifest_id",
    streamId: "stream_id",
  });
});

export function liveVideoToVideoParamsToJSON(
  liveVideoToVideoParams: LiveVideoToVideoParams,
): string {
  return JSON.stringify(
    LiveVideoToVideoParams$outboundSchema.parse(liveVideoToVideoParams),
  );
}
