/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Response model for live video-to-video generation.
 */
export type LiveVideoToVideoResponse = {
  /**
   * Source URL of the incoming stream to subscribe to
   */
  subscribeUrl: string;
  /**
   * Destination URL of the outgoing stream to publish to
   */
  publishUrl: string;
  /**
   * URL for updating the live video-to-video generation
   */
  controlUrl: string;
  /**
   * URL for subscribing to events for pipeline status and logs
   */
  eventsUrl: string;
  /**
   * The ID generated for this request
   */
  requestId: string;
  /**
   * Orchestrator manifest ID for this request
   */
  manifestId: string;
};

/** @internal */
export const LiveVideoToVideoResponse$inboundSchema: z.ZodType<
  LiveVideoToVideoResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  subscribe_url: z.string(),
  publish_url: z.string(),
  control_url: z.string().default(""),
  events_url: z.string().default(""),
  request_id: z.string().default(""),
  manifest_id: z.string().default(""),
}).transform((v) => {
  return remap$(v, {
    "subscribe_url": "subscribeUrl",
    "publish_url": "publishUrl",
    "control_url": "controlUrl",
    "events_url": "eventsUrl",
    "request_id": "requestId",
    "manifest_id": "manifestId",
  });
});

export function liveVideoToVideoResponseFromJSON(
  jsonString: string,
): SafeParseResult<LiveVideoToVideoResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LiveVideoToVideoResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LiveVideoToVideoResponse' from JSON`,
  );
}
