/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * Response model for live video-to-video generation.
 */
export type LiveVideoToVideoResponse = {
  /**
   * Source URL of the incoming stream to subscribe to
   */
  subscribeUrl: string;
  /**
   * Destination URL of the outgoing stream to publish to
   */
  publishUrl: string;
};

/** @internal */
export const LiveVideoToVideoResponse$inboundSchema: z.ZodType<
  LiveVideoToVideoResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  subscribe_url: z.string(),
  publish_url: z.string(),
}).transform((v) => {
  return remap$(v, {
    "subscribe_url": "subscribeUrl",
    "publish_url": "publishUrl",
  });
});

/** @internal */
export type LiveVideoToVideoResponse$Outbound = {
  subscribe_url: string;
  publish_url: string;
};

/** @internal */
export const LiveVideoToVideoResponse$outboundSchema: z.ZodType<
  LiveVideoToVideoResponse$Outbound,
  z.ZodTypeDef,
  LiveVideoToVideoResponse
> = z.object({
  subscribeUrl: z.string(),
  publishUrl: z.string(),
}).transform((v) => {
  return remap$(v, {
    subscribeUrl: "subscribe_url",
    publishUrl: "publish_url",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LiveVideoToVideoResponse$ {
  /** @deprecated use `LiveVideoToVideoResponse$inboundSchema` instead. */
  export const inboundSchema = LiveVideoToVideoResponse$inboundSchema;
  /** @deprecated use `LiveVideoToVideoResponse$outboundSchema` instead. */
  export const outboundSchema = LiveVideoToVideoResponse$outboundSchema;
  /** @deprecated use `LiveVideoToVideoResponse$Outbound` instead. */
  export type Outbound = LiveVideoToVideoResponse$Outbound;
}
