/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { LLMMessage, LLMMessage$inboundSchema } from "./llmmessage.js";

export type LLMChoice = {
  index: number;
  finishReason: string;
  delta?: LLMMessage | undefined;
  message?: LLMMessage | undefined;
};

/** @internal */
export const LLMChoice$inboundSchema: z.ZodType<
  LLMChoice,
  z.ZodTypeDef,
  unknown
> = z.object({
  index: z.number().int(),
  finish_reason: z.string().default(""),
  delta: LLMMessage$inboundSchema.optional(),
  message: LLMMessage$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "finish_reason": "finishReason",
  });
});

export function llmChoiceFromJSON(
  jsonString: string,
): SafeParseResult<LLMChoice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LLMChoice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LLMChoice' from JSON`,
  );
}
