/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  LLMMessage,
  LLMMessage$Outbound,
  LLMMessage$outboundSchema,
} from "./llmmessage.js";

export type LLMRequest = {
  messages: Array<LLMMessage>;
  model?: string | undefined;
  temperature?: number | undefined;
  maxTokens?: number | undefined;
  topP?: number | undefined;
  topK?: number | undefined;
  stream?: boolean | undefined;
};

/** @internal */
export type LLMRequest$Outbound = {
  messages: Array<LLMMessage$Outbound>;
  model: string;
  temperature: number;
  max_tokens: number;
  top_p: number;
  top_k: number;
  stream: boolean;
};

/** @internal */
export const LLMRequest$outboundSchema: z.ZodType<
  LLMRequest$Outbound,
  z.ZodTypeDef,
  LLMRequest
> = z.object({
  messages: z.array(LLMMessage$outboundSchema),
  model: z.string().default(""),
  temperature: z.number().default(0.7),
  maxTokens: z.number().int().default(256),
  topP: z.number().default(1),
  topK: z.number().int().default(-1),
  stream: z.boolean().default(false),
}).transform((v) => {
  return remap$(v, {
    maxTokens: "max_tokens",
    topP: "top_p",
    topK: "top_k",
  });
});

export function llmRequestToJSON(llmRequest: LLMRequest): string {
  return JSON.stringify(LLMRequest$outboundSchema.parse(llmRequest));
}
