/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { LLMChoice, LLMChoice$inboundSchema } from "./llmchoice.js";
import { LLMTokenUsage, LLMTokenUsage$inboundSchema } from "./llmtokenusage.js";

export type LLMResponse = {
  id: string;
  model: string;
  created: number;
  usage: LLMTokenUsage;
  choices: Array<LLMChoice>;
};

/** @internal */
export const LLMResponse$inboundSchema: z.ZodType<
  LLMResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  model: z.string(),
  created: z.number().int(),
  usage: LLMTokenUsage$inboundSchema,
  choices: z.array(LLMChoice$inboundSchema),
});

export function llmResponseFromJSON(
  jsonString: string,
): SafeParseResult<LLMResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LLMResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LLMResponse' from JSON`,
  );
}
