/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LLMTokenUsage = {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
};

/** @internal */
export const LLMTokenUsage$inboundSchema: z.ZodType<
  LLMTokenUsage,
  z.ZodTypeDef,
  unknown
> = z.object({
  prompt_tokens: z.number().int(),
  completion_tokens: z.number().int(),
  total_tokens: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "prompt_tokens": "promptTokens",
    "completion_tokens": "completionTokens",
    "total_tokens": "totalTokens",
  });
});

export function llmTokenUsageFromJSON(
  jsonString: string,
): SafeParseResult<LLMTokenUsage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LLMTokenUsage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LLMTokenUsage' from JSON`,
  );
}
