/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Response model for object segmentation.
 */
export type MasksResponse = {
  /**
   * The generated masks.
   */
  masks: string;
  /**
   * The model's confidence scores for each generated mask.
   */
  scores: string;
  /**
   * The raw, unnormalized predictions (logits) for the masks.
   */
  logits: string;
};

/** @internal */
export const MasksResponse$inboundSchema: z.ZodType<
  MasksResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  masks: z.string(),
  scores: z.string(),
  logits: z.string(),
});

export function masksResponseFromJSON(
  jsonString: string,
): SafeParseResult<MasksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MasksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MasksResponse' from JSON`,
  );
}
