/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A URL from which media can be accessed.
 */
export type MediaURL = {
  /**
   * The URL where the media can be accessed.
   */
  url: string;
};

/** @internal */
export const MediaURL$inboundSchema: z.ZodType<
  MediaURL,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string(),
});

export function mediaURLFromJSON(
  jsonString: string,
): SafeParseResult<MediaURL, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MediaURL$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MediaURL' from JSON`,
  );
}
