/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A media object containing information about the generated media.
 */
export type Media = {
  /**
   * The URL where the media can be accessed.
   */
  url: string;
  /**
   * The seed used to generate the media.
   */
  seed: number;
  /**
   * Whether the media was flagged as NSFW.
   */
  nsfw: boolean;
};

/** @internal */
export const Media$inboundSchema: z.ZodType<Media, z.ZodTypeDef, unknown> = z
  .object({
    url: z.string(),
    seed: z.number().int(),
    nsfw: z.boolean(),
  });

export function mediaFromJSON(
  jsonString: string,
): SafeParseResult<Media, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Media$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Media' from JSON`,
  );
}
