/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Chunk, Chunk$inboundSchema } from "./chunk.js";

/**
 * Response model for text generation.
 */
export type TextResponse = {
  /**
   * The generated text.
   */
  text: string;
  /**
   * The generated text chunks.
   */
  chunks: Array<Chunk>;
};

/** @internal */
export const TextResponse$inboundSchema: z.ZodType<
  TextResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  text: z.string(),
  chunks: z.array(Chunk$inboundSchema),
});

export function textResponseFromJSON(
  jsonString: string,
): SafeParseResult<TextResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TextResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextResponse' from JSON`,
  );
}
