/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type TextToSpeechParams = {
  /**
   * Hugging Face model ID used for text to speech generation.
   */
  modelId?: string | undefined;
  /**
   * Text input for speech generation.
   */
  text?: string | undefined;
  /**
   * Description of speaker to steer text to speech generation.
   */
  description?: string | undefined;
};

/** @internal */
export type TextToSpeechParams$Outbound = {
  model_id: string;
  text: string;
  description: string;
};

/** @internal */
export const TextToSpeechParams$outboundSchema: z.ZodType<
  TextToSpeechParams$Outbound,
  z.ZodTypeDef,
  TextToSpeechParams
> = z.object({
  modelId: z.string().default(""),
  text: z.string().default(""),
  description: z.string().default(
    "A male speaker delivers a slightly expressive and animated speech with a moderate speed and pitch.",
  ),
}).transform((v) => {
  return remap$(v, {
    modelId: "model_id",
  });
});

export function textToSpeechParamsToJSON(
  textToSpeechParams: TextToSpeechParams,
): string {
  return JSON.stringify(
    TextToSpeechParams$outboundSchema.parse(textToSpeechParams),
  );
}
